language: node_js
node_js:
    - v6
before_script:
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - 'npm install -g bower gulp-cli'
    - 'npm install'
    - 'bower install'
after_script:
    - 'npm test'
    - 'gulp coverage'
